/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { DrizzleToZeroSchema, ZeroCustomType } from 'drizzle-zero';
import type * as drizzleSchema from '../db/schema';

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    checkinsTable: {
      name: 'checkinsTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'checkinsTable',
            'id'
          >,
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'checkinsTable',
            'userId'
          >,
          serverName: 'user_id',
        },
        tournamentId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'checkinsTable',
            'tournamentId'
          >,
          serverName: 'tournament_id',
        },
        checkedOutAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'checkinsTable',
            'checkedOutAt'
          >,
          serverName: 'checked_out_at',
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'checkinsTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'checkins',
    },
    gamesTable: {
      name: 'gamesTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'id'
          >,
        },
        matchupId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'matchupId'
          >,
          serverName: 'matchup_id',
        },
        team1Id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'team1Id'
          >,
          serverName: 'team1_id',
        },
        team2Id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'team2Id'
          >,
          serverName: 'team2_id',
        },
        team1Score: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'team1Score'
          >,
          serverName: 'team1_score',
        },
        team2Score: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'team2Score'
          >,
          serverName: 'team2_score',
        },
        day: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'day'
          >,
        },
        tournamentId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'tournamentId'
          >,
          serverName: 'tournament_id',
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'gamesTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'games',
    },
    matchupsTable: {
      name: 'matchupsTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'matchupsTable',
            'id'
          >,
        },
        team1Id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'matchupsTable',
            'team1Id'
          >,
          serverName: 'team1_id',
        },
        team2Id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'matchupsTable',
            'team2Id'
          >,
          serverName: 'team2_id',
        },
        tournamentId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'matchupsTable',
            'tournamentId'
          >,
          serverName: 'tournament_id',
        },
        roundNumber: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'matchupsTable',
            'roundNumber'
          >,
          serverName: 'round_number',
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'matchupsTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'matchups',
    },
    teamsTable: {
      name: 'teamsTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'id'
          >,
        },
        name: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'name'
          >,
        },
        tournamentId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'tournamentId'
          >,
          serverName: 'tournament_id',
        },
        avgZScore: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'avgZScore'
          >,
          serverName: 'avg_z_score',
        },
        normalizedAvgZScore: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'normalizedAvgZScore'
          >,
          serverName: 'normalized_avg_z_score',
        },
        chemistry: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'chemistry'
          >,
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'version'
          >,
        },
        deletedAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsTable',
            'deletedAt'
          >,
          serverName: 'deleted_at',
        },
      },
      primaryKey: ['id'],
      serverName: 'teams',
    },
    teamsUsersTable: {
      name: 'teamsUsersTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsUsersTable',
            'id'
          >,
        },
        teamId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsUsersTable',
            'teamId'
          >,
          serverName: 'team_id',
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsUsersTable',
            'userId'
          >,
          serverName: 'user_id',
        },
        tournamentId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsUsersTable',
            'tournamentId'
          >,
          serverName: 'tournament_id',
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'teamsUsersTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'teams_users',
    },
    tournamentsTable: {
      name: 'tournamentsTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'tournamentsTable',
            'id'
          >,
        },
        name: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'tournamentsTable',
            'name'
          >,
        },
        day: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'tournamentsTable',
            'day'
          >,
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'tournamentsTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'tournaments',
    },
    userChemistriesTable: {
      name: 'userChemistriesTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'userChemistriesTable',
            'id'
          >,
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'userChemistriesTable',
            'userId'
          >,
          serverName: 'user_id',
        },
        withUserId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'userChemistriesTable',
            'withUserId'
          >,
          serverName: 'with_user_id',
        },
        chemistry: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'userChemistriesTable',
            'chemistry'
          >,
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'userChemistriesTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'user_chemistries',
    },
    usersTable: {
      name: 'usersTable',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'id'
          >,
        },
        name: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'name'
          >,
        },
        skillGroup: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'skillGroup'
          >,
          serverName: 'skill_group',
        },
        zScore: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'zScore'
          >,
          serverName: 'z_score',
        },
        sigma: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'sigma'
          >,
        },
        lastPlayedDay: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'lastPlayedDay'
          >,
          serverName: 'last_played_day',
        },
        gamesPlayed: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'gamesPlayed'
          >,
          serverName: 'games_played',
        },
        wins: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'wins'
          >,
        },
        pointsScored: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'pointsScored'
          >,
          serverName: 'points_scored',
        },
        pointsAllowed: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'pointsAllowed'
          >,
          serverName: 'points_allowed',
        },
        version: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            'usersTable',
            'version'
          >,
        },
      },
      primaryKey: ['id'],
      serverName: 'users',
    },
  },
  relationships: {},
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
